import nbformat as nbf
import google.generativeai as genai
import json
import os

class NotebookTools:

    def __init__(self):
        pass

    def _generate_gemini_insights(self, eda_output, model_output):
        """
        Creates AI-generated insights to embed inside the notebook.
        """

        try:
            # Load key from environment or Streamlit secrets
            api_key = os.environ.get("GOOGLE_API_KEY")

            if not api_key:
                return "LLM-generated narrative is unavailable because GOOGLE_API_KEY is not configured. The report contains computed tool outputs only."

            genai.configure(api_key=api_key)
            model = genai.GenerativeModel("gemini-1.5-flash")

            prompt = f"""
            You are a senior ML engineer generating insights for a professional ML report.

            Write:
            1. Key Data Findings from EDA
            2. Model Strengths & Weaknesses
            3. Suggested Next Steps
            4. Any potential risks in data or model

            Use the following JSON:
            EDA: {json.dumps(eda_output, indent=2)}
            MODEL: {json.dumps(model_output, indent=2)}
            """

            resp = model.generate_content(prompt)
            return resp.text

        except Exception:
            # Provider exceptions can contain request metadata; keep credentials and
            # sensitive response details out of generated artifacts.
            return "LLM-generated narrative could not be created. The report contains computed tool outputs only."


    def create_notebook(self, inputs):
        """
        inputs = {
            "profiler": {...},
            "eda": {...},
            "model": {...},
            "verifier": {...}
        }
        """

        nb = nbf.v4.new_notebook()
        cells = []

        # -------------------------------
        # TITLE PAGE
        # -------------------------------
        cells.append(nbf.v4.new_markdown_cell("# 📘 Auto-Generated Data Analysis Report"))
        cells.append(nbf.v4.new_markdown_cell("Generated by **AgenticDataLab**. Numerical sections contain tool-computed results; the optional narrative section is identified separately."))

        # -------------------------------
        # INPUT SECTIONS
        # -------------------------------
        for section, value in inputs.items():
            cells.append(
                nbf.v4.new_markdown_cell(f"## 🔍 {section.upper()} Output\n```json\n{json.dumps(value, indent=2)}\n```")
            )

        # -------------------------------
        # GEMINI ANALYSIS SECTION
        # -------------------------------
        gemini_insights = self._generate_gemini_insights(
            eda_output=inputs.get("eda", {}),
            model_output=inputs.get("model", {})
        )

        cells.append(
            nbf.v4.new_markdown_cell(
                "## Optional LLM-generated narrative (not a computed result)\n" +
                gemini_insights
            )
        )

        # -------------------------------
        # FINALIZE
        # -------------------------------
        nb["cells"] = cells
        nb_bytes = nbf.writes(nb).encode("utf-8")
        return nb_bytes
